M48
; DRILL file {KiCad 6.0.0+dfsg1-2} date ti 11. tammikuuta 2022 21.31.18
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-11T21:31:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0+dfsg1-2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.605Y-2.655
X4.83Y-2.955
T2
X4.13Y-2.69
X4.13Y-2.79
X4.13Y-2.89
X4.13Y-2.99
X4.285Y-2.99
T0
M30
